name: Docker Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest-crypto # specify runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker prerequisites
        run: |
          # Install iptables and other required dependencies
          sudo dnf install -y iptables iptables-nft iptables-legacy
          sudo dnf install -y device-mapper-persistent-data lvm2

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image-from-ci-cd-1:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image-from-ci-cd-1:latest